name: 'Resolves Runs On configuration'
description: 'Resolves Runs On configuration'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false
  main-repository:
    description: 'Full name of the main repository e.g. org/repository'
    required: true
  runs-on:
    description: 'Whether Runs-On is enabled'
    required: false
    default: 'false'
  spot:
    description: 'Whether to use Spot instances'
    required: false
    default: 'false'
  ubuntu-latest:
    description: 'Runs-On runner for ubuntu-latest'
    required: false
    default: 'family=m7i.xlarge/image=ubuntu24-full-x64'
outputs:
  config:
    value: ${{ steps.action.outputs.config }}

runs:
  using: "composite"
  steps:
    - name: Inject quarkus-github-action repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>quarkus-github-action</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>quarkus-github-action</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>quarkus-github-action</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi
    - name: Set up JBang
      uses: jbangdev/setup-jbang@main
    - name: Run the action
      id: action
      run: jbang --java 21 --fresh --repos 'quarkus-github-action=https://maven.pkg.github.com/quarkusio/runs-on-action/' --repos 'mavencentral' io.quarkus.bot:runs-on-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
